
pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar'
    organization: 'pruebacurso2'
    scannerMode: 'MSBuild'
    projectKey: 'pruebaCurso2_spring-boot-kubernetes'
    projectName: 'pruebacurso2'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: dependency-check-build-task@6
  inputs:
    projectName: 'spring-boot-kubernetes'
    scanPath: '''build/libs'''
    format: 'HTML'

- script: | 
    sudo apt-get install -y rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
    sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
    trivy image cotyc/labcurso:latest
  displayName: Image Scan